packages:
  - 'docs/'
  - 'example/'
  - 'packages/*'
  - 'tests/*'
catalog:
  'vite': ^6.2.2
  'vitest': ^3.0.8
  'typescript': ^5.8.2
catalogs:
  svelte:
    'svelte': ^5.23.0
    'svelte-check': ^4.1.5
    '@sveltejs/kit': ^2.19.0
    '@sveltejs/adapter-auto': ^4.0.0
    '@sveltejs/vite-plugin-svelte': ^5.0.3
    '@sveltejs/package': ^2.3.10
