packages:
  - 'docs/'
  - 'example/'
  - 'packages/*'
  - 'tests/*'
catalog:
  'vite': ^6.1.0
  'vitest': ^3.0.6
  'typescript': ^5.7.3
catalogs:
  svelte:
    'svelte': ^5.20.1
    'svelte-check': ^4.1.4
    '@sveltejs/kit': ^2.17.2
    '@sveltejs/adapter-auto': ^4.0.0
    '@sveltejs/vite-plugin-svelte': ^5.0.3
    '@sveltejs/package': ^2.3.10
