packages:
  - docs/
  - example/
  - packages/*
  - tests/*

minimumReleaseAge: 4320

engineStrict: true

allowBuilds:
  esbuild: true
  sharp: true

catalog:
  '@astrojs/check': ^0.9.9
  '@astrojs/starlight': ^0.39.2
  '@changesets/cli': ^2.31.0
  '@eslint/compat': ^2.1.0
  '@eslint/js': ^10.0.1
  '@playwright/test': ^1.60.0
  '@sveltejs/adapter-auto': ^7.0.1
  '@sveltejs/kit': ^2.60.1
  '@sveltejs/package': ^2.5.7
  '@sveltejs/vite-plugin-svelte': ^7.1.2
  '@types/eslint': ^9.6.1
  astro: ^6.3.1
  eslint: ^10.3.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-svelte: ^3.17.1
  globals: ^17.6.0
  prettier: ^3.8.3
  prettier-plugin-svelte: ^3.5.2
  publint: ^0.3.20
  sharp: ^0.34.5
  svelte: ^5.55.7
  svelte-check: ^4.4.8
  typescript: ^6.0.3
  typescript-eslint: ^8.59.3
  vite: ^8.0.12
  vitest: ^4.1.6
