packages:
  - 'docs/'
  - 'example/'
  - 'packages/*'
  - 'tests/*'
catalog:
  'vite': ^6.3.2
  'vitest': ^3.1.2
  'typescript': ^5.8.3
catalogs:
  svelte:
    'svelte': ^5.28.2
    'svelte-check': ^4.1.6
    '@sveltejs/kit': ^2.20.7
    '@sveltejs/adapter-auto': ^6.0.0
    '@sveltejs/vite-plugin-svelte': ^5.0.3
    '@sveltejs/package': ^2.3.11
