packages:
  - 'docs/'
  - 'example/'
  - 'packages/*'
  - 'tests/*'
catalog:
  'vite': ^6.2.4
  'vitest': ^3.1.1
  'typescript': ^5.8.2
catalogs:
  svelte:
    'svelte': ^5.25.5
    'svelte-check': ^4.1.5
    '@sveltejs/kit': ^2.20.2
    '@sveltejs/adapter-auto': ^5.0.0
    '@sveltejs/vite-plugin-svelte': ^5.0.3
    '@sveltejs/package': ^2.3.10
