packages:
  - docs/
  - example/
  - packages/*
  - tests/*

catalog:
  '@astrojs/check': ^0.9.6
  '@astrojs/starlight': ^0.37.4
  '@changesets/cli': ^2.29.8
  '@eslint/compat': ^2.0.1
  '@eslint/js': ^9.39.2
  '@playwright/test': ^1.57.0
  '@sveltejs/adapter-auto': ^7.0.0
  '@sveltejs/kit': ^2.50.0
  '@sveltejs/package': ^2.5.7
  '@sveltejs/vite-plugin-svelte': ^6.2.4
  '@types/eslint': ^9.6.1
  astro: ^5.16.15
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-svelte: ^3.14.0
  globals: ^17.0.0
  prettier: ^3.8.0
  prettier-plugin-svelte: ^3.4.1
  publint: ^0.3.16
  sharp: ^0.34.5
  svelte: ^5.47.1
  svelte-check: ^4.3.5
  typescript: ^5.9.3
  typescript-eslint: ^8.53.1
  vite: ^7.3.1
  vitest: ^4.0.17

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
  - sharp
