packages:
  - docs/
  - example/
  - packages/*
  - tests/*

catalog:
  '@astrojs/check': ^0.9.4
  '@astrojs/starlight': ^0.36.0
  '@changesets/cli': ^2.29.7
  '@eslint/compat': ^1.4.0
  '@eslint/js': ^9.37.0
  '@playwright/test': ^1.56.0
  '@sveltejs/adapter-auto': ^6.1.1
  '@sveltejs/kit': ^2.46.5
  '@sveltejs/package': ^2.5.4
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@types/eslint': ^9.6.1
  astro: ^5.14.5
  eslint: ^9.37.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-svelte: ^3.12.4
  globals: ^16.4.0
  prettier: ^3.6.2
  prettier-plugin-svelte: ^3.4.0
  publint: ^0.3.14
  sharp: ^0.34.4
  svelte: ^5.39.12
  svelte-check: ^4.3.3
  typescript: ^5.9.3
  typescript-eslint: ^8.46.1
  vite: ^7.1.9
  vitest: ^3.2.4

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
  - sharp
