packages:
  - docs/
  - example/
  - packages/*
  - tests/*

catalog:
  '@astrojs/check': ^0.9.6
  '@astrojs/starlight': ^0.37.0
  '@changesets/cli': ^2.29.8
  '@eslint/compat': ^2.0.0
  '@eslint/js': ^9.39.1
  '@playwright/test': ^1.57.0
  '@sveltejs/adapter-auto': ^7.0.0
  '@sveltejs/kit': ^2.49.1
  '@sveltejs/package': ^2.5.7
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@types/eslint': ^9.6.1
  astro: ^5.16.4
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-svelte: ^3.13.0
  globals: ^16.5.0
  prettier: ^3.7.3
  prettier-plugin-svelte: ^3.4.0
  publint: ^0.3.15
  sharp: ^0.34.5
  svelte: ^5.45.4
  svelte-check: ^4.3.4
  typescript: ^5.9.3
  typescript-eslint: ^8.48.1
  vite: ^7.2.6
  vitest: ^4.0.15

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
  - sharp
