packages:
  - docs/
  - example/
  - packages/*
  - tests/*

catalog:
  '@astrojs/check': ^0.9.5
  '@astrojs/starlight': ^0.36.1
  '@changesets/cli': ^2.29.7
  '@eslint/compat': ^1.4.0
  '@eslint/js': ^9.38.0
  '@playwright/test': ^1.56.1
  '@sveltejs/adapter-auto': ^7.0.0
  '@sveltejs/kit': ^2.47.3
  '@sveltejs/package': ^2.5.4
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@types/eslint': ^9.6.1
  astro: ^5.14.8
  eslint: ^9.38.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-svelte: ^3.12.5
  globals: ^16.4.0
  prettier: ^3.6.2
  prettier-plugin-svelte: ^3.4.0
  publint: ^0.3.15
  sharp: ^0.34.4
  svelte: ^5.42.1
  svelte-check: ^4.3.3
  typescript: ^5.9.3
  typescript-eslint: ^8.46.2
  vite: ^7.1.12
  vitest: ^4.0.3

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
  - sharp
