packages:
  - docs/
  - example/
  - packages/*
  - tests/*

catalog:
  '@astrojs/check': ^0.9.6
  '@astrojs/starlight': ^0.37.6
  '@changesets/cli': ^2.29.8
  '@eslint/compat': ^2.0.2
  '@eslint/js': ^9.39.2
  '@playwright/test': ^1.58.1
  '@sveltejs/adapter-auto': ^7.0.0
  '@sveltejs/kit': ^2.50.2
  '@sveltejs/package': ^2.5.7
  '@sveltejs/vite-plugin-svelte': ^6.2.4
  '@types/eslint': ^9.6.1
  astro: ^5.17.1
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-svelte: ^3.14.0
  globals: ^17.3.0
  prettier: ^3.8.1
  prettier-plugin-svelte: ^3.4.1
  publint: ^0.3.17
  sharp: ^0.34.5
  svelte: ^5.49.2
  svelte-check: ^4.3.6
  typescript: ^5.9.3
  typescript-eslint: ^8.54.0
  vite: ^7.3.1
  vitest: ^4.0.18

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
  - sharp
