packages:
  - 'docs/'
  - 'example/'
  - 'packages/*'
  - 'tests/*'
catalog:
  'vite': ^6.3.5
  'vitest': ^3.1.4
  'typescript': ^5.8.3
catalogs:
  svelte:
    'svelte': ^5.33.3
    'svelte-check': ^4.2.1
    '@sveltejs/kit': ^2.21.1
    '@sveltejs/adapter-auto': ^6.0.1
    '@sveltejs/vite-plugin-svelte': ^5.0.3
    '@sveltejs/package': ^2.3.11
onlyBuiltDependencies:
  - esbuild
  - sharp
