packages:
  - docs/
  - example/
  - packages/*
  - tests/*

catalog:
  vite: ^6.3.5
  vitest: ^3.2.4
  typescript: ^5.8.3

catalogs:
  svelte:
    svelte: ^5.34.7
    svelte-check: ^4.2.2
    '@sveltejs/kit': ^2.21.5
    '@sveltejs/adapter-auto': ^6.0.1
    '@sveltejs/vite-plugin-svelte': ^5.1.0
    '@sveltejs/package': ^2.3.11

onlyBuiltDependencies:
  - esbuild
  - sharp
