name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.changeset/**'
      - '.vscode/**'
      - '.husky/**'
      - '**/.github/**/*.md'
  pull_request:
    paths-ignore:
      - '.changeset/**'
      - '.vscode/**'
      - '.husky/**'
      - '**/.github/**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js and dependencies
        uses: ./.github/workflows/setup-node
      - name: Run Prettier check & ESLint
        run: pnpm lint

  check:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js and dependencies
        uses: ./.github/workflows/setup-node
      - name: Run svelte-package
        run: pnpm package
      - name: Run svelte-check
        run: pnpm check

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js and dependencies
        uses: ./.github/workflows/setup-node
      - name: Run svelte-package
        run: pnpm package
      - name: Run Build
        run: pnpm build
      - name: Setup Playwright
        uses: ./.github/workflows/setup-playwright
      - name: Run Vitest and Playwright
        run: pnpm test
