name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.changeset/**'
      - '.vscode/**'
      - '.husky/**'
      - '**/.github/**/*.md'
  pull_request:
    paths-ignore:
      - '.changeset/**'
      - '.vscode/**'
      - '.husky/**'
      - '**/.github/**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Node.js and dependencies
        uses: ./.github/workflows/setup-node
      - name: Run Prettier check & ESLint
        run: node --run lint

  check:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Node.js and dependencies
        uses: ./.github/workflows/setup-node
      - name: Run svelte-package
        run: node --run package
      - name: Run svelte-check
        run: node --run check

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Node.js and dependencies
        uses: ./.github/workflows/setup-node
      - name: Run svelte-package
        run: node --run package
      - name: Run Build
        run: node --run build
      - name: Setup Playwright
        uses: ./.github/workflows/setup-playwright
      - name: Run Vitest and Playwright
        run: node --run test
