name: Dependents Action

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  dependents:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: gouravkhunger/dependents.info@01650adc75c30ea62212ac7cc82c1a4153ccb2b3 # 0.1.6
