name: Dependents Action

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  dependents:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: gouravkhunger/dependents.info@bb3d55b67e0ec762dacb8c7456585a8464e14cb4 # 0.1.5
