name: Dependents Action

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  dependents:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: gouravkhunger/dependents.info@18ac9b82a1971134c9fbdefb577943191eb00266 # 0.1.4
