name: Deploy for Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get Node.js version from .npmrc
        id: get-node-version
        run: echo "node-version=$(grep '^use-node-version=' .npmrc | cut -d'=' -f2)" >> "$GITHUB_OUTPUT"
      - name: Get pnpm version from package.json
        id: get-pnpm-version
        run: echo "pnpm-version=$(node -p "require('./package.json').packageManager")" >> "$GITHUB_OUTPUT"
      - name: Install, build, and upload your site
        uses: withastro/action@b7d53628f8b666036b0238aadb0b984a2a489f26 # v6.1.1
        with:
          path: docs
          node-version: ${{ steps.get-node-version.outputs.node-version }}
          package-manager: ${{ steps.get-pnpm-version.outputs.pnpm-version }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
